// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
	public class SharedController
	{

		static readonly ViewsClass s_views = new ViewsClass();
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public ViewsClass Views { get { return s_views; } }
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ViewsClass
		{
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Partial_Dialog_Loading = "_Partial_Dialog_Loading";
                public readonly string _Partial_Dialog_Message = "_Partial_Dialog_Message";
            }
            public readonly string _Partial_Dialog_Loading = "~/Views/Shared/_Partial_Dialog_Loading.cshtml";
            public readonly string _Partial_Dialog_Message = "~/Views/Shared/_Partial_Dialog_Message.cshtml";
            static readonly _LayoutsClass s_Layouts = new _LayoutsClass();
            public _LayoutsClass Layouts { get { return s_Layouts; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _LayoutsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _Layout_Default = "_Layout_Default";
                }
                public readonly string _Layout_Default = "~/Views/Shared/Layouts/_Layout_Default.cshtml";
            }
            static readonly _PartialViewsClass s_PartialViews = new _PartialViewsClass();
            public _PartialViewsClass PartialViews { get { return s_PartialViews; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _PartialViewsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                }
                static readonly _MvcFileManagerClass s_MvcFileManager = new _MvcFileManagerClass();
                public _MvcFileManagerClass MvcFileManager { get { return s_MvcFileManager; } }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public partial class _MvcFileManagerClass
                {
                    static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                    public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                    public class _ViewNamesClass
                    {
                        public readonly string _Partial_Buttons = "_Partial_Buttons";
                        public readonly string _Partial_Dialog_General = "_Partial_Dialog_General";
                        public readonly string _Partial_DirectoriesArea = "_Partial_DirectoriesArea";
                        public readonly string _Partial_DirectoriesArea_Buttons = "_Partial_DirectoriesArea_Buttons";
                        public readonly string _Partial_DirectoriesArea_SortingAndFiltering = "_Partial_DirectoriesArea_SortingAndFiltering";
                        public readonly string _Partial_DirectoriesArea_Table = "_Partial_DirectoriesArea_Table";
                        public readonly string _Partial_FileManager = "_Partial_FileManager";
                        public readonly string _Partial_FilesArea = "_Partial_FilesArea";
                        public readonly string _Partial_FilesArea_Buttons = "_Partial_FilesArea_Buttons";
                        public readonly string _Partial_FilesArea_SortingAndFiltering = "_Partial_FilesArea_SortingAndFiltering";
                        public readonly string _Partial_FilesArea_Table = "_Partial_FilesArea_Table";
                        public readonly string _Partial_Path = "_Partial_Path";
                        public readonly string _Partial_UploadFile = "_Partial_UploadFile";
                    }
                    public readonly string _Partial_Buttons = "~/Views/Shared/PartialViews/MvcFileManager/_Partial_Buttons.cshtml";
                    public readonly string _Partial_Dialog_General = "~/Views/Shared/PartialViews/MvcFileManager/_Partial_Dialog_General.cshtml";
                    public readonly string _Partial_DirectoriesArea = "~/Views/Shared/PartialViews/MvcFileManager/_Partial_DirectoriesArea.cshtml";
                    public readonly string _Partial_DirectoriesArea_Buttons = "~/Views/Shared/PartialViews/MvcFileManager/_Partial_DirectoriesArea_Buttons.cshtml";
                    public readonly string _Partial_DirectoriesArea_SortingAndFiltering = "~/Views/Shared/PartialViews/MvcFileManager/_Partial_DirectoriesArea_SortingAndFiltering.cshtml";
                    public readonly string _Partial_DirectoriesArea_Table = "~/Views/Shared/PartialViews/MvcFileManager/_Partial_DirectoriesArea_Table.cshtml";
                    public readonly string _Partial_FileManager = "~/Views/Shared/PartialViews/MvcFileManager/_Partial_FileManager.cshtml";
                    public readonly string _Partial_FilesArea = "~/Views/Shared/PartialViews/MvcFileManager/_Partial_FilesArea.cshtml";
                    public readonly string _Partial_FilesArea_Buttons = "~/Views/Shared/PartialViews/MvcFileManager/_Partial_FilesArea_Buttons.cshtml";
                    public readonly string _Partial_FilesArea_SortingAndFiltering = "~/Views/Shared/PartialViews/MvcFileManager/_Partial_FilesArea_SortingAndFiltering.cshtml";
                    public readonly string _Partial_FilesArea_Table = "~/Views/Shared/PartialViews/MvcFileManager/_Partial_FilesArea_Table.cshtml";
                    public readonly string _Partial_Path = "~/Views/Shared/PartialViews/MvcFileManager/_Partial_Path.cshtml";
                    public readonly string _Partial_UploadFile = "~/Views/Shared/PartialViews/MvcFileManager/_Partial_UploadFile.cshtml";
                }
            }
		}
	}

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
